version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "80:8000"
    environment:
      - NODE_ENV
    depends_on:
      - redis
  redis:
    image: redis:5.0.0
    ports:
      - "6379:6379"
